[2023-03-28T22:39:44.495+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_uniprot_Q9Y261.write_subcellular_locations manual__2023-03-28T22:39:37.958043+00:00 [queued]>
[2023-03-28T22:39:44.518+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_uniprot_Q9Y261.write_subcellular_locations manual__2023-03-28T22:39:37.958043+00:00 [queued]>
[2023-03-28T22:39:44.519+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T22:39:44.520+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-28T22:39:44.522+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T22:39:44.548+0000] {taskinstance.py:1303} INFO - Executing <Task(_PythonDecoratedOperator): write_subcellular_locations> on 2023-03-28 22:39:37.958043+00:00
[2023-03-28T22:39:44.558+0000] {standard_task_runner.py:55} INFO - Started process 1372 to run task
[2023-03-28T22:39:44.562+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_uniprot_Q9Y261', 'write_subcellular_locations', 'manual__2023-03-28T22:39:37.958043+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/uniprot_Q9Y261/main.py', '--cfg-path', '/tmp/tmpn9gme3v_']
[2023-03-28T22:39:44.563+0000] {standard_task_runner.py:83} INFO - Job 130: Subtask write_subcellular_locations
[2023-03-28T22:39:44.718+0000] {task_command.py:388} INFO - Running <TaskInstance: etl_uniprot_Q9Y261.write_subcellular_locations manual__2023-03-28T22:39:37.958043+00:00 [running]> on host 147865a62ab8
[2023-03-28T22:39:44.937+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_uniprot_Q9Y261
AIRFLOW_CTX_TASK_ID=write_subcellular_locations
AIRFLOW_CTX_EXECUTION_DATE=2023-03-28T22:39:37.958043+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-28T22:39:37.958043+00:00
[2023-03-28T22:39:44.942+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/uniprot_Q9Y261/main.py", line 151, in write_subcellular_locations
    if isinstance(location.get("location"), list):
AttributeError: 'NoneType' object has no attribute 'get'
[2023-03-28T22:39:44.987+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=etl_uniprot_Q9Y261, task_id=write_subcellular_locations, execution_date=20230328T223937, start_date=20230328T223944, end_date=20230328T223944
[2023-03-28T22:39:45.016+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 130 for task write_subcellular_locations ('NoneType' object has no attribute 'get'; 1372)
[2023-03-28T22:39:45.060+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-28T22:39:45.128+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
